### ISSUE TITLE
Add API Documentation

### ISSUE THREAD

**Issue by danr789** [MrLetsplay2003/ShittyAuthServer#3]
I have the Server setup and ready to go, but cannot seem to use any launcher apart from yours. Trying to implement this server into another client using the authlib-injector seems to fail, can you document the API so we can Implement it into other launchers as well?

**Comment by MrLetsplay2003** [comment]
What exactly doesn't work when using another client? Can you not log in, are there any weird errors? The API is mostly just a reimplementation of the Yggdrasil API, as well as the legacy Mojang skin/cape APIs

**Comment by danr789** [comment]
I'm using this as my launcher : https://github.com/Voxelum/x-minecraft-launcher 

And I get this error when trying to login :
<img width="411" alt="image" src="https://user-images.githubusercontent.com/86713549/189882404-4813bfd4-2f75-47d9-98db-fb4f997de812.png">

This is my config:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/86713549/189882841-1e45396a-a65a-429f-8863-4355a28ea74c.png">

Getting this error :
`me.mrletsplay.mrcore.json.JSONParseException: Invalid generic value:  (at char 0)
        at me.mrletsplay.mrcore.json.JSONParser.readGeneric(JSONParser.java:109)
        at me.mrletsplay.mrcore.json.JSONParser.parse(JSONParser.java:27)
        at me.mrletsplay.mrcore.json.JSONObject.<init>(JSONObject.java:31)
        at me.mrletsplay.simplehttpserver.http.header.DefaultClientContentTypes.lambda$static$1(DefaultClientContentTypes.java:20)
        at me.mrletsplay.simplehttpserver.http.header.DefaultClientContentTypes.parse(DefaultClientContentTypes.java:53)
        at me.mrletsplay.simplehttpserver.http.header.PostData.getParsedAs(PostData.java:22)
        at me.mrletsplay.shittyauth.page.api.yggdrasil.AuthenticatePage.createContent(AuthenticatePage.java:26)
        at me.mrletsplay.simplehttpserver.http.HttpConnection.receive(HttpConnection.java:100)
        at me.mrletsplay.simplehttpserver.http.HttpConnection.lambda$startRecieving$0(HttpConnection.java:53)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by MrLetsplay2003** [comment]
There appears to be some strange bug in the HTTP server, I'll try to fix it

**Comment by danr789** [comment]
Alright, this seems mostly fixed, just that API is sent as a HTML response instead of JSON
