### ISSUE TITLE
Uploading a Skin is not possible

### ISSUE THREAD

**Issue by x0rp01s0n** [MrLetsplay2003/ShittyAuthServer#5]
**Problem:**
When uploading a skin, i get Malformed request.

**What i did yet:**
Fresh setup with MariaDB, created admin account setup https -> working,
created minecraft account with admin account, uploaded skin -> malformed request
same when trying to upload a cape.
also tryed the same without ssl, same result.

**backend log:**
```
MoTTY X11 proxy: Unsupported authorisation protocol
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at me.mrletsplay.webinterfaceapi.page.action.ActionHandler.handle(ActionHandler.java:28)
        at me.mrletsplay.webinterfaceapi.page.action.WebinterfaceActionHandlers.handle(WebinterfaceActionHandlers.java:13)
        at me.mrletsplay.webinterfaceapi.document.FileUploadDocument.createContent(FileUploadDocument.java:47)
        at me.mrletsplay.simplehttpserver.http.HttpConnection.receive(HttpConnection.java:100)
        at me.mrletsplay.simplehttpserver.http.HttpConnection.lambda$startRecieving$0(HttpConnection.java:53)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at me.mrletsplay.shittyauth.webinterface.ShittyAuthWIHandler.uploadSkin(ShittyAuthWIHandler.java:64)
        ... 14 more
2023-01-31 17:44:06 [pool-3-thread-13 | Webinterface] ERROR: Malformed request
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at me.mrletsplay.webinterfaceapi.page.action.ActionHandler.handle(ActionHandler.java:28)
        at me.mrletsplay.webinterfaceapi.page.action.WebinterfaceActionHandlers.handle(WebinterfaceActionHandlers.java:13)
        at me.mrletsplay.webinterfaceapi.document.FileUploadDocument.createContent(FileUploadDocument.java:47)
        at me.mrletsplay.simplehttpserver.http.HttpConnection.receive(HttpConnection.java:100)
        at me.mrletsplay.simplehttpserver.http.HttpConnection.lambda$startRecieving$0(HttpConnection.java:53)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at me.mrletsplay.shittyauth.webinterface.ShittyAuthWIHandler.uploadSkin(ShittyAuthWIHandler.java:64)
        ... 14 common frames omitted
```

**frontend (browser):**

no errors in console,
seems like backend to me.
![image](https://user-images.githubusercontent.com/43322985/215842336-fe997de7-43ea-4c4f-b4fb-c1d035d1e9db.png)
![image](https://user-images.githubusercontent.com/43322985/215842940-49c4c43c-c751-4425-9b37-33b5e98d3e1b.png)
![image](https://user-images.githubusercontent.com/43322985/215842977-45f72a58-27c4-44e5-92b2-3bf7a8def148.png)

**Comment by MrLetsplay2003** [comment]
Looks like you're possibly missing a library the JVM requires to create a graphics environment. According to [this](https://support.xilinx.com/s/question/0D52E00007EwEesSAF/install-hangs-at-generating-installed-device-list?language=en_US) post, installing `libtinfo5` might fix the issue.

It could also be that you're running a headless JVM that does not provide a graphics environment at all.

**Comment by x0rp01s0n** [comment]
OK so i solved it by typing: `unset DISPLAY` before running the server,
it seems like java tryed to reach out for a non existing x11 display, also installing the library you provided.
